models.py
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class User:
    _id: str
    email: str
    password: str
    confirmed: bool
    confirmed_on: datetime
    books: list[dict] = field(default_factory=list)
    pages: list[dict] = field(default_factory=list)

forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, SubmitField, EmailField, DateField, StringField, IntegerField
from wtforms.validators import InputRequired, Email, Length, EqualTo, NumberRange


class LoginForm(FlaskForm):
    email = EmailField("Email", validators=[InputRequired()])
    password = PasswordField("Password", validators=[InputRequired()])
    submit = SubmitField("Login")


class RegisterForm(FlaskForm):
    email = EmailField("Email", validators=[InputRequired(), Email()])
    password = PasswordField(
        'Password',
        validators=[
            InputRequired(), Length(4, 20),
            EqualTo('confirm',
                    message='Passwords must match')
        ])
    confirm = PasswordField('Repeat Password')
    submit = SubmitField("Register")


class AddBook(FlaskForm):
    book = StringField("Book", validators=[InputRequired()])
    date = DateField("Date", validators=[InputRequired()])
    submit = SubmitField("Add book")


class AddPages(FlaskForm):
    page = IntegerField("Page",
                        validators=[
                            InputRequired(),
                            NumberRange(min=0, max=999, message="Type a number between 1-999")
                        ])
    date = DateField("Date", validators=[InputRequired()])
    submit = SubmitField("Add pages")

app.py
import os
from datetime import timedelta

from dotenv import load_dotenv
from flask import Flask, session
from flask_mail import Mail
from pymongo import MongoClient

from routes import pages

load_dotenv()
mail = Mail()


def create_app():
    app = Flask(__name__)

    @app.before_request
    def before_request():
        session.permanent = True
        app.permanent_session_lifetime = timedelta(minutes=120)

    app.secret_key = os.environ.get("SECRET_KEY")
    app.config["SECURITY_PASSWORD_SALT"] = os.environ.get("SECURITY_PASSWORD_SALT")
    app.config["MONGODB_URI"] = os.environ.get("MONGODB_URI")
    app.config['MAIL_SERVER'] = os.environ.get("MAIL_SERVER")
    app.config['MAIL_PORT'] = os.environ.get("MAIL_PORT")
    app.config['MAIL_USERNAME'] = os.environ.get("MAIL_USERNAME")
    app.config['MAIL_PASSWORD'] = os.environ.get("MAIL_PASSWORD")
    app.config['MAIL_USE_SSL'] = os.environ.get("MAIL_USE_SSL")
    app.db = MongoClient(app.config["MONGODB_URI"]).get_default_database()
    app.mail = Mail(app)
    app.register_blueprint(pages)
    return app

routes.py
import datetime
import functools
import uuid
from dataclasses import asdict

from flask import Blueprint, render_template, session, redirect, url_for, request, make_response, current_app, flash
from passlib.hash import pbkdf2_sha256

from forms import LoginForm, RegisterForm, AddBook, AddPages
from mail_token import generate_confirmation_token, confirm_token
from models import User
from mail_sender import send_email

pages = Blueprint("books", __name__, template_folder="templates", static_folder="static")


def login_required(route):
    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if not session.get("email"):
            return redirect(url_for("books.login"))
        return route(*args, **kwargs)

    return route_wrapper


def date_list(date=None):
    selected_date = datetime.datetime.strptime(date, "%d/%m/%Y") if date else datetime.date.today()
    dates = [(selected_date + datetime.timedelta(day)).strftime("%d/%m/%Y") for day in range(-3, 4)]
    return dates


@pages.route("/", methods=["GET", "POST"])
@login_required
def index():
    email, date = session.get("email"), request.args.get("date")
    user_data = current_app.db.user.find_one({"email": email})
    books = user_data["books"]
    pages_ = user_data["pages"]
    dates = date_list(date)
    daily_pages = dict()
    for date in dates:
        for item in pages_:
            if item["date"] == date:
                daily_pages[date] = item["page"]
    return render_template("index.html", title="Home page", books=books, dates=dates, daily_pages=daily_pages)


@pages.route("/add-book", methods=["GET", "POST"])
@login_required
def add_book():
    form = AddBook()
    email, is_valid, book, date = session.get("email"), form.validate_on_submit(), form.book.data, form.date.data
    if is_valid:
        date = datetime.datetime.strftime(date, "%d/%m/%Y")
        current_app.db.user.update_one({"email": email}, {"$push": {"books": {"book": book, "date": date}}})
        return redirect(url_for("books.index"))
    return render_template("add_book.html", title="Add book", form=form)


@pages.route("/add-pages", methods=["GET", "POST"])
@login_required
def add_pages():
    form = AddPages()
    email, is_valid, page, date = session.get("email"), form.validate_on_submit(), form.page.data, form.date.data
    if is_valid:
        date = datetime.datetime.strftime(date, "%d/%m/%Y")
        current_app.db.user.update_one({"email": email}, {"$push": {"pages": {"page": page, "date": date}}})
        return redirect(url_for("books.index"))
    return render_template("add_page.html", title="Add page", form=form)


@pages.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    is_valid, email, password = form.validate_on_submit(), form.email.data, form.password.data
    if is_valid:
        user_data = current_app.db.user.find_one({"email": email})

        if user_data and pbkdf2_sha256.verify(password, user_data["password"]):
            session["email"] = email
            return redirect(url_for("books.index"))
        return make_response("Wrong username or password", 403)
    return render_template("login.html", title="Login form", form=form)


@pages.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    is_valid, email, password = form.validate_on_submit(), form.email.data, form.password.data
    if is_valid:
        user_data = current_app.db.user.find_one({"email": email})
        if user_data:
            return make_response("User already exists.", 401)
        user = User(
            _id=uuid.uuid4().hex,
            email=form.email.data,
            password=pbkdf2_sha256.hash(form.password.data),
            confirmed=False,
            confirmed_on=None
        )

        current_app.db.user.insert_one(asdict(user))
        token = generate_confirmation_token(user.email)
        confirm_url = url_for('books.confirm_email', token=token, _external=True)
        html = render_template('activate.html', confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(user.email, subject, html)
        flash('A confirmation email has been sent via email.', 'success')
        return redirect(url_for("books.login"))
    return render_template("register.html", title="Register form", form=form)


@pages.route('/confirm/<token>')
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    user = User(**current_app.db.user.find_one({"email": email}))
    if user.confirmed:
        flash('Account already confirmed. Please login.', 'success')
    else:
        user.confirmed = True
        user.confirmed_on = datetime.datetime.now()
        current_app.db.user.update_one({"email": email},
                                       {"$set": {"confirmed": user.confirmed, "confirmed_on": user.confirmed_on}})
        flash('You have confirmed your account. Thanks!', 'success')
    return redirect(url_for('books.index'))


@pages.route("/logout", methods=["GET"])
def logout():
    session.clear()
    return redirect(url_for("books.login"))

templates/activate.html
<p>Welcome! Thanks for signing up. Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Cheers!</p>

templates/add_book.html
{% extends "layout.html" %}

{% block main_block %}
<form class="form" method="post" name="login">
    <div class="form__container">
        {{ form.hidden_tag() }}
        {{ form.book(class_="form__field", placeholder="Add book") }}
        {{ form.date(class="form__field", placeholder="Add date") }}
        {{ form.submit(class_="form__button") }}
    </div>
</form>
{% endblock %}

templates/add_page.html
{% extends "layout.html" %}

{% block main_block %}
<form class="form" method="post" name="login">
    <div class="form__container">
        {{ form.hidden_tag() }}
        {{ form.page(class_="form__field", placeholder="Add page") }}
        {{ form.date(class="form__field", placeholder="Add date") }}
        {{ form.submit(class_="form__button") }}
    </div>
</form>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block main_block %}
<section class="dates">
    {% for date in dates %}
    <div class="date">
    <a class="date__link" href="{{ url_for('books.index', date=date) }}" methods="post">{{ date }}</a>
    <p class="date__pages {{ 'date__pages-zero' if daily_pages.get(date, 0) == 0 else '' }}">{{ daily_pages.get(date, 0) }}</p>
    </div>
    {% endfor %}
</section>
<section class="books">
    {% for item in books %}
    <p class="book"><span>{{ item.get("book") }}</span><span>{{ item.get("date") }}</span></p>
    {% endfor %}
</section>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css' ) }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css' ) }}">
</head>
<body class="body">
<header class="header">
    <section class="navigation">
    <div class="logo"><p class="logo__name">Book Journal</p></div>
    <div class="navbar">
        <a class="navbar__link" href="{{ url_for('books.index') }}">Home</a>
        <a class="navbar__link" href="{{ url_for('books.add_book') }}">Add Book</a>
        <a class="navbar__link" href="{{ url_for('books.add_pages') }}">Add Pages</a>
        {% if not session.get("email") %}
        <a class="navbar__link" href="{{ url_for('books.login') }}">Login</a>
        {% else %}
        <a class="navbar__link" href="{{ url_for('books.logout') }}">Logout</a>
        {% endif %}
    </div>
    </section>
</header>
<main class="main"> {% block main_block %}{% endblock %} </main>
<footer class="footer"><p class="footer__text">made by cetin 2022</p></footer>
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block main_block %}
<form class="form" method="post" name="login">
    <div class="form__container">
        {{ form.hidden_tag() }}
        {{ form.email(class_="form__field", placeholder="email@email.com") }}
        {{ form.password(class="form__field", placeholder="password") }}
        {{ form.submit(class_="form__button") }}
        <p>Don't have an account, <a class="form__container-link" href="{{ url_for('books.register') }}">register!</a></p>
    </div>
</form>
{% endblock %}

templates/register.html
{% extends "layout.html" %}

{% block main_block %}
<form class="form" method="post" name="login">
    <div class="form__container">
        {{ form.hidden_tag() }}
        {{ form.email(class_="form__field", placeholder="email@email.com") }}
        {{ form.password(class="form__field", placeholder="password") }}
        {{ form.confirm(class="form__field", placeholder="confirm") }}
        {{ form.submit(class_="form__button") }}
    </div>
</form>
{% endblock %}